### PR TITLE
Add missing non-serveradmin roles

### PR DESCRIPTION
**Pull request by anghelmihai**

### CODE REVIEW

**Comment by tun0** [comment]
While we're at it, anything else on https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#privileges-provided-summary that might be needed as well? :wink:

**Comment by tun0** [comment]
> While we're at it, anything else on https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#privileges-provided-summary that might be needed as well? 😉

There's some stuff related to views, stored routines, etc which might be useful as well to include?

**Comment by anghelmihai** [comment]
> > While we're at it, anything else on https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#privileges-provided-summary that might be needed as well? 😉
> 
> There's some stuff related to views, stored routines, etc which might be useful as well to include?


We don't use views and stored routines. About other privileges, I'd say no but everytime I added a new privilege I said the same thing :))

**Comment by tun0** [comment]
> > > While we're at it, anything else on https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#privileges-provided-summary that might be needed as well? 😉
> > 
> > 
> > There's some stuff related to views, stored routines, etc which might be useful as well to include?
> 
> We don't use views and stored routines. About other privileges, I'd say no but everytime I added a new privilege I said the same thing :))

You never know what the future might bring though. So, I just added all non-serveradmin ones anyway :wink:

**Review by tun0 — APPROVED** [review]

**Pull request merged**
